name: Build OrangeFox R12 Tucana

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Recovery
    runs-on: ubuntu-22.04
    steps:
    - name: Clean disk space
      uses: rokibhasansagar/slimhub_actions@main

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python2
        sudo ln -sf /usr/bin/python2 /usr/bin/python
        
        sudo curl https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod a+x /usr/local/bin/repo
        
        git config --global user.name "LIECOTI"
        git config --global user.email "liecoti@github.com"

    - name: Sync OrangeFox sources
      run: |
        mkdir ~/OrangeFox_sync
        cd ~/OrangeFox_sync
        git clone https://gitlab.com/OrangeFox/sync.git
        cd sync
        ./orangefox_sync.sh --branch 12.1 --path ~/fox_12.1

    - name: Clone device tree and download DTBO
      run: |
        cd ~/fox_12.1
        git clone https://github.com/LIECOTI/tucana-orangefox.git -b not_retrofit device/xiaomi/tucana
        cd device/xiaomi/tucana
        curl -L -o dtbo.img "https://mirrors.dotsrc.org/lineageos/full/tucana/20260601/dtbo.img"
  
    - name: Build OrangeFox
      run: |
        cd ~/fox_12.1
        set -x
        set +e
        export ALLOW_MISSING_DEPENDENCIES=true
        export FOX_BUILD_DEVICE=tucana
        export LC_ALL="C"
        export OF_FORCE_PREBUILT_KERNEL=1
        source build/envsetup.sh
        lunch twrp_tucana-eng
        mka adbd recoveryimage

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: OrangeFox-Tucana-NOT-Retrofit
        path: ~/fox_12.1/out/target/product/tucana/OrangeFox*.zip
